server:
  tomcat:
    uri-encoding: UTF-8
  port: 8060

logging:
  level:
    org.springframework.web: ERROR
    org.web3j.protocol.core: DEBUG
    io.keyko: DEBUG
    io.keyko.monitoring.agent.core.configs: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
  file: /logs/application.log

spring:
  data:
    mongodb.uri: ${MONGO_DB_URI:mongodb://localhost:27017/test}
  output:
  ansi:
    enabled: DETECT

ethereum:
  client:
    address: "0xab9c2c7afe19b9491e654b3ca1f20aaf34776802"
  nodes:
  - name: default
    url: ${ETHEREUM_NODE_URL:http://localhost:8545}
    blockStrategy: POLL
    syncingThreshold: 100
    healthcheckInterval: 3000
    readTimeout: 120000
  healthcheck:
    pollInterval: 2000
  blockStrategy: POLL


eventStore:
  type: DB
  url: http://localhost:8081/api/rest/v1
  eventPath: /event
  latestBlockPath: /latestblock
database:
  type: MONGO

broadcaster:
  type: KAFKA
  cache:
    expirationMillis: 6000000
  event:
    confirmation:
      numBlocksToWait: 12
      numBlocksToWaitForMissingTx: 100
      numBlocksToWaitBeforeInvalidating: 2
  multiInstance: false
  enableBlockNotifications: true

# For Kafka
zookeeper:
  address: ${ZOOKEEPER_ADDRESS:localhost:2181}
kafka:
  bootstrap:
    addresses: ${KAFKA_ADDRESSES:localhost:9092}
  topic:
    contractEvents: w3m-contract-events
    contractViews: w3m-contract-views
    blockEvents: w3m-block-events
    eventeumEvents: w3m-eventeum-events
    transactionEvents: w3m-transaction-events
    logs:  w3m-logs

    partitions: 1
    replicationSets: 1
  schemaRegistry:
    url: ${KAFKA_SCHEMAREGISTRY_URL:http://localhost:18081}

management:
  endpoints:
    web.base-path: /monitoring
    enabled-by-default: false
    web.exposure.include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: false
    prometheus:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: false


eventFilters:
#  - id: EpochRewardsDistributedToVoters
#    contractAddress: "0xC8FD77490A12F46709BffbCC0FCe35740Da8D860"
#    eventSpecification:
#      eventName: EpochRewardsDistributedToVoters
#      indexedParameterDefinitions:
#        - position: 0
#          type: ADDRESS
#          name: group
#      nonIndexedParameterDefinitions:
#        - position: 0
#          type: UINT256
#          name: value
#    correlationId:
#      type: NON_INDEXED_PARAMETER
#      index: 0

#transactionFilters:
#- nodeName: ${ETHEREUM_NETWORK:DefaultNetwork}
#  type: "FROM_ADDRESS"
#  transactionIdentifierValue: ${CONTRACT_ADDRESS_EM_TOKEN:0x0f8E7A681019Ec13EfE853a6Eca666E05b214Fd5}
#  statuses: ['CONFIRMED']
#- nodeName: ${ETHEREUM_NETWORK:DefaultNetwork}
#  type: "TO_ADDRESS"
#  transactionIdentifierValue: ${CONTRACT_ADDRESS_EM_TOKEN:0xfBAB8dE62002c86986C6e070BD3bB46BF983C74e}
#  statuses: ['FAILED']

